// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDld9065T1xpHSgcSSkDs2g6kok3UbvLog',
    appId: '1:749798274410:web:6f365215d7c3cbc17da113',
    messagingSenderId: '749798274410',
    projectId: 'workout-builder-3207b',
    authDomain: 'workout-builder-3207b.firebaseapp.com',
    databaseURL: 'https://workout-builder-3207b.firebaseio.com',
    storageBucket: 'workout-builder-3207b.appspot.com',
    measurementId: 'G-1VRYRCQPLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2pnN-GTLvRQExh0sg2dMj7Qkphh8lKGk',
    appId: '1:749798274410:android:b2916a45cdb0efb27da113',
    messagingSenderId: '749798274410',
    projectId: 'workout-builder-3207b',
    databaseURL: 'https://workout-builder-3207b.firebaseio.com',
    storageBucket: 'workout-builder-3207b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzp_kUgAfkZnPvlQucygUezC37vqHaTa8',
    appId: '1:749798274410:ios:f65a4999f50a85ef7da113',
    messagingSenderId: '749798274410',
    projectId: 'workout-builder-3207b',
    databaseURL: 'https://workout-builder-3207b.firebaseio.com',
    storageBucket: 'workout-builder-3207b.appspot.com',
    iosClientId: '749798274410-13qe8vq94l3ijuk3q5av7vslhnu41qmf.apps.googleusercontent.com',
    iosBundleId: 'com.ftness.fitnessSimplified',
  );
}
